### PR TITLE
Add licenses for the project

### PR DESCRIPTION
**Pull request by samrocketman**
After Zoura approves I will reorganize the history so that the license applies to all older commits.

Two licenses are added.

* For images see the summary for [Creative Commons Share-Alike 4.0][cc].
* For game data (and all files, code, scripts, etc) the [GPLv3 License applies][gpl].

[cc]: https://creativecommons.org/licenses/by-sa/4.0/
[gpl]: https://www.gnu.org/licenses/gpl-3.0.html

### CODE REVIEW

**Comment by samrocketman** [comment]
# Approve license changes

Click on "Files changed" and follow these three steps to approve the license changes.

Screenshot taken at 2022-03-10_21-20-53

**Review by AvianGeneticist — CHANGES_REQUESTED** [review]
In "copyright", I'd like the description to be changed, since the old description is leftover from another plugin of mine I took the description from (totally my fault, sorry for the inconvenience).
From the current
" An endless sky plugin that just aims to flesh out the game with a wide variety
 of changes, ranging from experimental weapons to the expansion of both Human
 and Hai space, as well as a whole new (in-development) galaxy."
To
"An endless sky plugin that adds an extremely powerful set of ships and missions
accessed via a custom start, intended for testing other extremely strong plugin
factions or just generally playing around with."

**Review by AvianGeneticist — APPROVED** [review]

**Comment by samrocketman** [comment]
Updated copyright text to

> An endless sky plugin that adds an extremely powerful set of ships and missions
accessed via a custom start, intended for testing other extremely strong plugin
factions or just generally playing around with.

Also updated image copyright to add:

> ...Quaernan ship and companion ships

**Comment by samrocketman** [comment]
Rebased history where commit aaa118f01d825728221f0b88d330d1e73fbe5dff got a new hash c94776bfe288051a61d367e3f38db99605534167 when I re-organized it before initial data imports for Zoura

**Pull request merged**
